version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Point to prod Dockerfile
    container_name: flixtr-be-prod
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    network_mode: host

networks:
  nginx-proxy:
    external: true