version: '3.8'
services:
  backend:
    build: .
    container_name: flixtr-be-dev
    restart: unless-stopped
    ports:
      - "6006:6006" # Dev port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    networks:
      - nginx-proxy
    extra_hosts:
      - "host.docker.internal:10.0.1.1"

networks:
  nginx-proxy:
    external: true