# Production Dockerfile
FROM node:16.14.0-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --include=dev  # Install TypeScript
COPY . .
RUN npm run build  # Compile TS->JS

FROM node:16.14.0-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./

# Configure npm
RUN npm config set update-notifier false --global

CMD ["node", "build/index.js"]  # Directly run compiled JS