version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Point to dev Dockerfile
    container_name: flixtr-be-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    network_mode: host

networks:
  nginx-proxy:
    external: true