name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'

          # Ensure nvm is sourced
          source /home/ubuntu/.nvm/nvm.sh

          cd /home/ubuntu/Desktop/flixtr-be

          # Discard local changes to package-lock.json or other files
          git reset --hard HEAD

          docker-compose -f docker-compose.yml down
          docker system prune -f

          git pull origin main
          echo "${{ secrets.PRODUCTION_ENV }}" > .env.production
          docker-compose -f docker-compose.yml build --no-cache
          docker-compose -f docker-compose.yml up -d
          EOF
